// Generated from `toolSubsectionsForGroup` -- see lib/tools/browse.ts for why,
// and browse.test.ts, which fails if this file drifts from the catalogue.
import type { BrowseSection } from '../browse';

export const SECTIONS: readonly BrowseSection[] = [
  {
    id: 'calculators',
    title: 'Calculators & units',
    description: 'Percentages, arithmetic, formulas, and unit conversion.',
    destinations: [
      {
        id: 'percentage-calculator',
        name: 'Percentage calculator',
        description: 'Calculate percentages, ratios, and percentage change.',
        href: '/math/percentage-calculator',
        workspaceId: 'percentage-calculator',
      },
      {
        id: 'math-workbench:basic-calculator',
        name: 'Basic calculator',
        description:
          'Evaluate arithmetic with +, −, ×, ÷, %, powers, and parentheses.',
        href: '/math/workbench?tool=basic-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:fraction-calculator',
        name: 'Fraction calculator',
        description: 'Add, subtract, multiply, or divide two fractions.',
        href: '/math/workbench?tool=fraction-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:ratio-calculator',
        name: 'Ratio calculator',
        description: 'Reduce an integer ratio to lowest terms.',
        href: '/math/workbench?tool=ratio-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:proportion-calculator',
        name: 'Proportion calculator',
        description: 'Solve a:b = c:x.',
        href: '/math/workbench?tool=proportion-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:average-calculator',
        name: 'Average calculator',
        description: 'Calculate the arithmetic mean of a number list.',
        href: '/math/workbench?tool=average-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:median-calculator',
        name: 'Median calculator',
        description: 'Calculate the middle value of a number list.',
        href: '/math/workbench?tool=median-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:mode-calculator',
        name: 'Mode calculator',
        description: 'Find every most-frequent value in a number list.',
        href: '/math/workbench?tool=mode-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:variance-calculator',
        name: 'Variance calculator',
        description: 'Calculate population variance.',
        href: '/math/workbench?tool=variance-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:standard-deviation-calculator',
        name: 'Standard-deviation calculator',
        description: 'Calculate population standard deviation.',
        href: '/math/workbench?tool=standard-deviation-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:probability-calculator',
        name: 'Probability calculator',
        description: 'Calculate favorable outcomes divided by total outcomes.',
        href: '/math/workbench?tool=probability-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:permutation-calculator',
        name: 'Permutation calculator',
        description: 'Calculate nPr for whole numbers.',
        href: '/math/workbench?tool=permutation-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:combination-calculator',
        name: 'Combination calculator',
        description: 'Calculate nCr for whole numbers.',
        href: '/math/workbench?tool=combination-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:prime-number-checker',
        name: 'Prime-number checker',
        description: 'Check a safe positive integer for primality.',
        href: '/math/workbench?tool=prime-number-checker',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:prime-factorization',
        name: 'Prime factorization',
        description: 'Factor a positive safe integer up to one trillion.',
        href: '/math/workbench?tool=prime-factorization',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:gcd-calculator',
        name: 'GCD calculator',
        description: 'Find the greatest common divisor of two integers.',
        href: '/math/workbench?tool=gcd-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:lcm-calculator',
        name: 'LCM calculator',
        description: 'Find the least common multiple of two integers.',
        href: '/math/workbench?tool=lcm-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:quadratic-equation-solver',
        name: 'Quadratic-equation solver',
        description: 'Solve ax² + bx + c = 0, including complex roots.',
        href: '/math/workbench?tool=quadratic-equation-solver',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:linear-equation-solver',
        name: 'Linear-equation solver',
        description: 'Solve ax + b = 0.',
        href: '/math/workbench?tool=linear-equation-solver',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:logarithm-calculator',
        name: 'Logarithm calculator',
        description: 'Calculate log base b of x.',
        href: '/math/workbench?tool=logarithm-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:exponent-calculator',
        name: 'Exponent calculator',
        description: 'Calculate base raised to an exponent.',
        href: '/math/workbench?tool=exponent-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:root-calculator',
        name: 'Root calculator',
        description: 'Calculate an nth root with real-number validation.',
        href: '/math/workbench?tool=root-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:scientific-calculator',
        name: 'Scientific calculator',
        description:
          'Apply a common scientific function with explicit degrees or radians.',
        href: '/math/workbench?tool=scientific-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:system-of-equations-solver',
        name: 'System-of-equations solver',
        description: 'Solve a 2×2 linear system a₁x+b₁y=c₁ and a₂x+b₂y=c₂.',
        href: '/math/workbench?tool=system-of-equations-solver',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:matrix-calculator',
        name: 'Matrix calculator',
        description: 'Add, subtract, or multiply bounded numeric matrices.',
        href: '/math/workbench?tool=matrix-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:determinant-calculator',
        name: 'Determinant calculator',
        description: 'Calculate a determinant for a square matrix up to 6×6.',
        href: '/math/workbench?tool=determinant-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:complex-number-calculator',
        name: 'Complex-number calculator',
        description:
          'Add, subtract, multiply, or divide a+bi coordinate pairs.',
        href: '/math/workbench?tool=complex-number-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:geometry-calculator',
        name: 'Geometry calculator',
        description: 'Calculate area and perimeter for a selected 2D shape.',
        href: '/math/workbench?tool=geometry-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:volume-calculator',
        name: 'Volume calculator',
        description: 'Calculate common solid volumes from explicit dimensions.',
        href: '/math/workbench?tool=volume-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:surface-area-calculator',
        name: 'Surface-area calculator',
        description: 'Calculate total surface area for common closed solids.',
        href: '/math/workbench?tool=surface-area-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:fuel-economy-converter',
        name: 'Fuel-economy converter',
        description: 'Convert L/100 km, US MPG, and imperial MPG.',
        href: '/math/workbench?tool=fuel-economy-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:number-to-words',
        name: 'Number to words',
        description:
          'Spell a safe whole number up to 999,999,999,999 in English.',
        href: '/math/workbench?tool=number-to-words',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:words-to-number',
        name: 'Words to number',
        description:
          'Parse supported English whole-number words up to billions.',
        href: '/math/workbench?tool=words-to-number',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:significant-figures-calculator',
        name: 'Significant-figures calculator',
        description:
          'Round a finite non-zero number to 1–100 significant figures.',
        href: '/math/workbench?tool=significant-figures-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:margin-of-error-calculator',
        name: 'Margin-of-error calculator',
        description:
          'Calculate z × sample deviation ÷ √n with an explicit z score.',
        href: '/math/workbench?tool=margin-of-error-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:confidence-interval-calculator',
        name: 'Confidence-interval calculator',
        description:
          'Calculate a normal-approximation mean interval from mean, deviation, n, and z.',
        href: '/math/workbench?tool=confidence-interval-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:z-score-calculator',
        name: 'Z-score calculator',
        description:
          'Calculate (value − mean) ÷ population standard deviation.',
        href: '/math/workbench?tool=z-score-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:percentile-calculator',
        name: 'Percentile calculator',
        description:
          'Interpolate a requested percentile in a finite number list.',
        href: '/math/workbench?tool=percentile-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:correlation-calculator',
        name: 'Correlation calculator',
        description:
          'Calculate Pearson correlation for two equal-length lists.',
        href: '/math/workbench?tool=correlation-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:linear-regression-calculator',
        name: 'Linear-regression calculator',
        description: 'Fit the least-squares line y = intercept + slope × x.',
        href: '/math/workbench?tool=linear-regression-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:sample-size-calculator',
        name: 'Sample-size calculator',
        description:
          'Estimate a proportion sample size z²p(1−p)/e² before finite-population correction.',
        href: '/math/workbench?tool=sample-size-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:triangle-calculator',
        name: 'Triangle calculator',
        description: 'Calculate area from base and perpendicular height.',
        href: '/math/workbench?tool=triangle-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:circle-calculator',
        name: 'Circle calculator',
        description: 'Calculate area, circumference, and diameter from radius.',
        href: '/math/workbench?tool=circle-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:rectangle-calculator',
        name: 'Rectangle calculator',
        description: 'Calculate area, perimeter, and diagonal.',
        href: '/math/workbench?tool=rectangle-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:polygon-calculator',
        name: 'Regular-polygon calculator',
        description:
          'Calculate perimeter and area from side count and side length.',
        href: '/math/workbench?tool=polygon-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:temperature-converter',
        name: 'Temperature converter',
        description: 'Convert Celsius, Fahrenheit, and Kelvin.',
        href: '/math/workbench?tool=temperature-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:roman-numeral-converter',
        name: 'Roman-numeral converter',
        description:
          'Convert integers 1–3999 to Roman numerals or parse canonical Roman numerals.',
        href: '/math/workbench?tool=roman-numeral-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:scientific-notation-converter',
        name: 'Scientific-notation converter',
        description: 'Show a finite number in normalized scientific notation.',
        href: '/math/workbench?tool=scientific-notation-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:rounding-calculator',
        name: 'Rounding calculator',
        description:
          'Round a finite number to a chosen number of decimal places.',
        href: '/math/workbench?tool=rounding-calculator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:random-number-generator',
        name: 'Random-number generator',
        description: 'Generate random integers in an inclusive range.',
        href: '/math/workbench?tool=random-number-generator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:dice-roller',
        name: 'Dice roller',
        description: 'Roll one to 100 dice with two to 1,000 sides.',
        href: '/math/workbench?tool=dice-roller',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:coin-flipper',
        name: 'Coin flipper',
        description: 'Flip one to 100 fair virtual coins.',
        href: '/math/workbench?tool=coin-flipper',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:sequence-generator',
        name: 'Sequence generator',
        description: 'Generate an arithmetic sequence.',
        href: '/math/workbench?tool=sequence-generator',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:distance-converter',
        name: 'Distance converter',
        description: 'Convert metric, imperial, and nautical distances.',
        href: '/math/workbench?tool=distance-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:area-converter',
        name: 'Area converter',
        description: 'Convert common metric and imperial areas.',
        href: '/math/workbench?tool=area-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:volume-converter',
        name: 'Volume converter',
        description: 'Convert metric and common liquid volumes.',
        href: '/math/workbench?tool=volume-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:mass-converter',
        name: 'Mass converter',
        description: 'Convert metric and imperial mass units.',
        href: '/math/workbench?tool=mass-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:speed-converter',
        name: 'Speed converter',
        description: 'Convert speed units using exact standard factors.',
        href: '/math/workbench?tool=speed-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:time-unit-converter',
        name: 'Time-unit converter',
        description: 'Convert elapsed-time units.',
        href: '/math/workbench?tool=time-unit-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:pressure-converter',
        name: 'Pressure converter',
        description: 'Convert pascals and common engineering pressure units.',
        href: '/math/workbench?tool=pressure-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:energy-converter',
        name: 'Energy converter',
        description: 'Convert joules, watt-hours, calories, and BTU.',
        href: '/math/workbench?tool=energy-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:power-converter',
        name: 'Power converter',
        description: 'Convert watts and common power units.',
        href: '/math/workbench?tool=power-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:force-converter',
        name: 'Force converter',
        description: 'Convert newtons and common force units.',
        href: '/math/workbench?tool=force-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:torque-converter',
        name: 'Torque converter',
        description: 'Convert newton-metres and common torque units.',
        href: '/math/workbench?tool=torque-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:angle-converter',
        name: 'Angle converter',
        description: 'Convert degrees, radians, gradians, and turns.',
        href: '/math/workbench?tool=angle-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:frequency-converter',
        name: 'Frequency converter',
        description: 'Convert hertz and common frequency scales.',
        href: '/math/workbench?tool=frequency-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:data-size-converter',
        name: 'Data-size converter',
        description: 'Convert decimal and binary byte units.',
        href: '/math/workbench?tool=data-size-converter',
        workspaceId: 'math-workbench',
      },
      {
        id: 'math-workbench:cooking-unit-converter',
        name: 'Cooking-unit converter',
        description:
          'Convert volume-only cooking measures without assuming ingredient density.',
        href: '/math/workbench?tool=cooking-unit-converter',
        workspaceId: 'math-workbench',
      },
    ],
  },
];
