/**
 * Guide consolidation switch (owner decision: keep full guides only for the
 * tools that earn search traffic or have something distinct to say; send the
 * rest to their tool page with a 301 and drop them from the sitemap).
 *
 * ON since 2026-09-21, by owner decision. Search Console still has no rows --
 * the property was new when the owner checked on 2026-09-17 -- so the 15 kept
 * guides in lib/seo/guide-keep-list.ts were chosen on the evidence
 * `npm run seo:guide-distinctness` measures rather than on traffic. The
 * traffic path is unchanged and waits for the first export.
 *
 * Turning this back to `false` restores the previous site exactly: every live
 * guide renders again and returns to the sitemap. Browsers may hold the 301s
 * for a while; search engines recrawl.
 *
 * Runbook: docs/seo/guide-consolidation.md. The keep list it acts on is
 * lib/seo/guide-keep-list.ts, generated by scripts/guide-keep-list.mjs.
 */
export const GUIDE_CONSOLIDATION_ENABLED = true;
