/**
 * Guide consolidation switch (owner decision: keep full guides only for the
 * tools that earn search traffic or have something distinct to say; send the
 * rest to their tool page with a 301 and drop them from the sitemap).
 *
 * Enable only after the owner supplies Search Console data (DECISION_LOG §11).
 * The owner checked on 2026-09-17: the property was new and the Performance
 * report had no rows, so there is nothing to select on yet and this stays
 * `false`. While it is `false` the site behaves exactly as it did before this
 * mechanism existed -- no URL changes, no sitemap changes, no link changes.
 *
 * Runbook: docs/seo/guide-consolidation.md. The keep list it acts on is
 * lib/seo/guide-keep-list.ts, generated by scripts/guide-keep-list.mjs.
 */
export const GUIDE_CONSOLIDATION_ENABLED = false;
