/**
 * Comprehensive LaTeX symbol catalog with search and category filtering.
 */

export interface LatexSymbol {
  command: string;
  symbol: string;
  name: string;
  category:
    | 'greek'
    | 'operators'
    | 'relations'
    | 'arrows'
    | 'delimiters'
    | 'accents'
    | 'misc';
  mathMode: boolean;
  package?: string;
  tags: readonly string[];
}

export const LATEX_SYMBOLS: readonly LatexSymbol[] = [
  // Greek Lowercase
  {
    command: '\\alpha',
    symbol: 'α',
    name: 'Alpha',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'letter', 'angle'],
  },
  {
    command: '\\beta',
    symbol: 'β',
    name: 'Beta',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'letter'],
  },
  {
    command: '\\gamma',
    symbol: 'γ',
    name: 'Gamma',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'letter'],
  },
  {
    command: '\\delta',
    symbol: 'δ',
    name: 'Delta',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'difference', 'letter'],
  },
  {
    command: '\\epsilon',
    symbol: 'ϵ',
    name: 'Epsilon',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'small'],
  },
  {
    command: '\\varepsilon',
    symbol: 'ε',
    name: 'Varepsilon',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'small'],
  },
  {
    command: '\\zeta',
    symbol: 'ζ',
    name: 'Zeta',
    category: 'greek',
    mathMode: true,
    tags: ['greek'],
  },
  {
    command: '\\eta',
    symbol: 'η',
    name: 'Eta',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'efficiency'],
  },
  {
    command: '\\theta',
    symbol: 'θ',
    name: 'Theta',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'angle'],
  },
  {
    command: '\\vartheta',
    symbol: 'ϑ',
    name: 'Vartheta',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'angle'],
  },
  {
    command: '\\iota',
    symbol: 'ι',
    name: 'Iota',
    category: 'greek',
    mathMode: true,
    tags: ['greek'],
  },
  {
    command: '\\kappa',
    symbol: 'κ',
    name: 'Kappa',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'curvature'],
  },
  {
    command: '\\lambda',
    symbol: 'λ',
    name: 'Lambda',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'wavelength', 'eigenvalue'],
  },
  {
    command: '\\mu',
    symbol: 'μ',
    name: 'Mu',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'micro', 'mean'],
  },
  {
    command: '\\nu',
    symbol: 'ν',
    name: 'Nu',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'frequency'],
  },
  {
    command: '\\xi',
    symbol: 'ξ',
    name: 'Xi',
    category: 'greek',
    mathMode: true,
    tags: ['greek'],
  },
  {
    command: '\\pi',
    symbol: 'π',
    name: 'Pi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'circle', 'constant', '3.14'],
  },
  {
    command: '\\rho',
    symbol: 'ρ',
    name: 'Rho',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'density'],
  },
  {
    command: '\\sigma',
    symbol: 'σ',
    name: 'Sigma',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'variance', 'standard deviation'],
  },
  {
    command: '\\tau',
    symbol: 'τ',
    name: 'Tau',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'torque', 'time'],
  },
  {
    command: '\\upsilon',
    symbol: 'υ',
    name: 'Upsilon',
    category: 'greek',
    mathMode: true,
    tags: ['greek'],
  },
  {
    command: '\\phi',
    symbol: 'ϕ',
    name: 'Phi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'golden ratio', 'angle'],
  },
  {
    command: '\\varphi',
    symbol: 'φ',
    name: 'Varphi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'angle'],
  },
  {
    command: '\\chi',
    symbol: 'χ',
    name: 'Chi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'distribution'],
  },
  {
    command: '\\psi',
    symbol: 'ψ',
    name: 'Psi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'wavefunction'],
  },
  {
    command: '\\omega',
    symbol: 'ω',
    name: 'Omega',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'angular frequency'],
  },

  // Greek Uppercase
  {
    command: '\\Gamma',
    symbol: 'Γ',
    name: 'Capital Gamma',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'capital'],
  },
  {
    command: '\\Delta',
    symbol: 'Δ',
    name: 'Capital Delta',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'change', 'triangle', 'laplacian'],
  },
  {
    command: '\\Theta',
    symbol: 'Θ',
    name: 'Capital Theta',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'capital'],
  },
  {
    command: '\\Lambda',
    symbol: 'Λ',
    name: 'Capital Lambda',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'capital'],
  },
  {
    command: '\\Xi',
    symbol: 'Ξ',
    name: 'Capital Xi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'capital'],
  },
  {
    command: '\\Pi',
    symbol: 'Π',
    name: 'Capital Pi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'product', 'capital'],
  },
  {
    command: '\\Sigma',
    symbol: 'Σ',
    name: 'Capital Sigma',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'sum', 'capital'],
  },
  {
    command: '\\Upsilon',
    symbol: 'Υ',
    name: 'Capital Upsilon',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'capital'],
  },
  {
    command: '\\Phi',
    symbol: 'Φ',
    name: 'Capital Phi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'flux', 'capital'],
  },
  {
    command: '\\Psi',
    symbol: 'Ψ',
    name: 'Capital Psi',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'capital'],
  },
  {
    command: '\\Omega',
    symbol: 'Ω',
    name: 'Capital Omega',
    category: 'greek',
    mathMode: true,
    tags: ['greek', 'ohm', 'resistance', 'capital'],
  },

  // Operators
  {
    command: '\\pm',
    symbol: '±',
    name: 'Plus-minus',
    category: 'operators',
    mathMode: true,
    tags: ['plus', 'minus', 'tolerance'],
  },
  {
    command: '\\times',
    symbol: '×',
    name: 'Times / Cross product',
    category: 'operators',
    mathMode: true,
    tags: ['multiply', 'cross'],
  },
  {
    command: '\\div',
    symbol: '÷',
    name: 'Division',
    category: 'operators',
    mathMode: true,
    tags: ['divide'],
  },
  {
    command: '\\cdot',
    symbol: '·',
    name: 'Center dot',
    category: 'operators',
    mathMode: true,
    tags: ['multiply', 'dot product'],
  },
  {
    command: '\\cap',
    symbol: '∩',
    name: 'Intersection',
    category: 'operators',
    mathMode: true,
    tags: ['set', 'cap'],
  },
  {
    command: '\\cup',
    symbol: '∪',
    name: 'Union',
    category: 'operators',
    mathMode: true,
    tags: ['set', 'cup'],
  },
  {
    command: '\\vee',
    symbol: '∨',
    name: 'Logical or / Vee',
    category: 'operators',
    mathMode: true,
    tags: ['logic', 'or'],
  },
  {
    command: '\\wedge',
    symbol: '∧',
    name: 'Logical and / Wedge',
    category: 'operators',
    mathMode: true,
    tags: ['logic', 'and'],
  },
  {
    command: '\\oplus',
    symbol: '⊕',
    name: 'Circled plus / Direct sum',
    category: 'operators',
    mathMode: true,
    tags: ['xor', 'direct sum'],
  },
  {
    command: '\\otimes',
    symbol: '⊗',
    name: 'Circled times / Tensor product',
    category: 'operators',
    mathMode: true,
    tags: ['tensor', 'product'],
  },
  {
    command: '\\int',
    symbol: '∫',
    name: 'Integral',
    category: 'operators',
    mathMode: true,
    tags: ['calculus', 'integrate'],
  },
  {
    command: '\\iint',
    symbol: '∬',
    name: 'Double integral',
    category: 'operators',
    mathMode: true,
    package: 'amsmath',
    tags: ['calculus', 'area'],
  },
  {
    command: '\\oint',
    symbol: '∮',
    name: 'Contour integral',
    category: 'operators',
    mathMode: true,
    tags: ['calculus', 'contour', 'closed'],
  },
  {
    command: '\\sum',
    symbol: '∑',
    name: 'Summation',
    category: 'operators',
    mathMode: true,
    tags: ['sum', 'series', 'total'],
  },
  {
    command: '\\prod',
    symbol: '∏',
    name: 'Product',
    category: 'operators',
    mathMode: true,
    tags: ['product', 'series'],
  },
  {
    command: '\\partial',
    symbol: '∂',
    name: 'Partial derivative',
    category: 'operators',
    mathMode: true,
    tags: ['calculus', 'derivative'],
  },
  {
    command: '\\nabla',
    symbol: '∇',
    name: 'Nabla / Del / Gradient',
    category: 'operators',
    mathMode: true,
    tags: ['gradient', 'divergence', 'curl', 'vector'],
  },
  {
    command: '\\infty',
    symbol: '∞',
    name: 'Infinity',
    category: 'operators',
    mathMode: true,
    tags: ['limit', 'unbounded'],
  },
  {
    command: '\\sqrt{x}',
    symbol: '√',
    name: 'Square root',
    category: 'operators',
    mathMode: true,
    tags: ['root', 'radical'],
  },

  // Relations
  {
    command: '\\leq',
    symbol: '≤',
    name: 'Less than or equal',
    category: 'relations',
    mathMode: true,
    tags: ['inequality', 'compare'],
  },
  {
    command: '\\geq',
    symbol: '≥',
    name: 'Greater than or equal',
    category: 'relations',
    mathMode: true,
    tags: ['inequality', 'compare'],
  },
  {
    command: '\\neq',
    symbol: '≠',
    name: 'Not equal',
    category: 'relations',
    mathMode: true,
    tags: ['not equal', 'compare'],
  },
  {
    command: '\\approx',
    symbol: '≈',
    name: 'Approximately equal',
    category: 'relations',
    mathMode: true,
    tags: ['approx', 'estimate'],
  },
  {
    command: '\\equiv',
    symbol: '≡',
    name: 'Identical / Equivalent / Congruent',
    category: 'relations',
    mathMode: true,
    tags: ['identity', 'modulo'],
  },
  {
    command: '\\sim',
    symbol: '∼',
    name: 'Similar / Distributed as',
    category: 'relations',
    mathMode: true,
    tags: ['proportional', 'probability'],
  },
  {
    command: '\\subset',
    symbol: '⊂',
    name: 'Proper subset',
    category: 'relations',
    mathMode: true,
    tags: ['set', 'included'],
  },
  {
    command: '\\subseteq',
    symbol: '⊆',
    name: 'Subset or equal',
    category: 'relations',
    mathMode: true,
    tags: ['set', 'included'],
  },
  {
    command: '\\in',
    symbol: '∈',
    name: 'Element of',
    category: 'relations',
    mathMode: true,
    tags: ['set', 'belongs', 'member'],
  },
  {
    command: '\\notin',
    symbol: '∉',
    name: 'Not an element of',
    category: 'relations',
    mathMode: true,
    tags: ['set', 'member'],
  },
  {
    command: '\\propto',
    symbol: '∝',
    name: 'Proportional to',
    category: 'relations',
    mathMode: true,
    tags: ['proportion', 'scale'],
  },
  {
    command: '\\ll',
    symbol: '≪',
    name: 'Much less than',
    category: 'relations',
    mathMode: true,
    tags: ['comparison'],
  },
  {
    command: '\\gg',
    symbol: '≫',
    name: 'Much greater than',
    category: 'relations',
    mathMode: true,
    tags: ['comparison'],
  },
  {
    command: '\\perp',
    symbol: '⊥',
    name: 'Perpendicular / Orthogonal',
    category: 'relations',
    mathMode: true,
    tags: ['orthogonal', 'normal'],
  },
  {
    command: '\\parallel',
    symbol: '∥',
    name: 'Parallel',
    category: 'relations',
    mathMode: true,
    tags: ['parallel', 'geometry'],
  },

  // Arrows
  {
    command: '\\leftarrow',
    symbol: '←',
    name: 'Left arrow',
    category: 'arrows',
    mathMode: true,
    tags: ['arrow', 'left'],
  },
  {
    command: '\\rightarrow',
    symbol: '→',
    name: 'Right arrow',
    category: 'arrows',
    mathMode: true,
    tags: ['arrow', 'right', 'implies', 'limit'],
  },
  {
    command: '\\leftrightarrow',
    symbol: '↔',
    name: 'Left-right arrow',
    category: 'arrows',
    mathMode: true,
    tags: ['arrow', 'bidirectional'],
  },
  {
    command: '\\Leftarrow',
    symbol: '⇐',
    name: 'Double left arrow',
    category: 'arrows',
    mathMode: true,
    tags: ['arrow', 'left'],
  },
  {
    command: '\\Rightarrow',
    symbol: '⇒',
    name: 'Implies / Double right arrow',
    category: 'arrows',
    mathMode: true,
    tags: ['implies', 'logic'],
  },
  {
    command: '\\Leftrightarrow',
    symbol: '⇔',
    name: 'If and only if / IFF',
    category: 'arrows',
    mathMode: true,
    tags: ['iff', 'equivalence', 'logic'],
  },
  {
    command: '\\uparrow',
    symbol: '↑',
    name: 'Up arrow',
    category: 'arrows',
    mathMode: true,
    tags: ['arrow', 'up'],
  },
  {
    command: '\\downarrow',
    symbol: '↓',
    name: 'Down arrow',
    category: 'arrows',
    mathMode: true,
    tags: ['arrow', 'down'],
  },
  {
    command: '\\mapsto',
    symbol: '↦',
    name: 'Maps to',
    category: 'arrows',
    mathMode: true,
    tags: ['function', 'mapping'],
  },

  // Delimiters
  {
    command: '\\{ \\}',
    symbol: '{ }',
    name: 'Set braces',
    category: 'delimiters',
    mathMode: true,
    tags: ['bracket', 'set'],
  },
  {
    command: '\\lfloor \\rfloor',
    symbol: '⌊ ⌋',
    name: 'Floor brackets',
    category: 'delimiters',
    mathMode: true,
    tags: ['round down', 'math'],
  },
  {
    command: '\\lceil \\rceil',
    symbol: '⌈ ⌉',
    name: 'Ceiling brackets',
    category: 'delimiters',
    mathMode: true,
    tags: ['round up', 'math'],
  },
  {
    command: '\\langle \\rangle',
    symbol: '⟨ ⟩',
    name: 'Angle brackets / Bra-ket',
    category: 'delimiters',
    mathMode: true,
    tags: ['inner product', 'physics', 'quantum'],
  },
  {
    command: '\\| \\|',
    symbol: '‖ ‖',
    name: 'Double vertical bars / Norm',
    category: 'delimiters',
    mathMode: true,
    tags: ['norm', 'magnitude'],
  },

  // Miscellaneous
  {
    command: '\\forall',
    symbol: '∀',
    name: 'For all (Universal quantifier)',
    category: 'misc',
    mathMode: true,
    tags: ['logic', 'all'],
  },
  {
    command: '\\exists',
    symbol: '∃',
    name: 'There exists (Existential quantifier)',
    category: 'misc',
    mathMode: true,
    tags: ['logic', 'exists'],
  },
  {
    command: '\\nexists',
    symbol: '∄',
    name: 'There does not exist',
    category: 'misc',
    mathMode: true,
    package: 'amssymb',
    tags: ['logic'],
  },
  {
    command: '\\empty',
    symbol: '∅',
    name: 'Empty set',
    category: 'misc',
    mathMode: true,
    tags: ['null', 'set', 'void'],
  },
  {
    command: '\\mathbb{R}',
    symbol: 'ℝ',
    name: 'Real numbers',
    category: 'misc',
    mathMode: true,
    package: 'amssymb',
    tags: ['reals', 'math'],
  },
  {
    command: '\\mathbb{N}',
    symbol: 'ℕ',
    name: 'Natural numbers',
    category: 'misc',
    mathMode: true,
    package: 'amssymb',
    tags: ['naturals', 'math'],
  },
  {
    command: '\\mathbb{Z}',
    symbol: 'ℤ',
    name: 'Integers',
    category: 'misc',
    mathMode: true,
    package: 'amssymb',
    tags: ['integers', 'math'],
  },
  {
    command: '\\mathbb{C}',
    symbol: 'ℂ',
    name: 'Complex numbers',
    category: 'misc',
    mathMode: true,
    package: 'amssymb',
    tags: ['complex', 'math'],
  },
  {
    command: '\\dots',
    symbol: '…',
    name: 'Ellipsis',
    category: 'misc',
    mathMode: false,
    tags: ['dots', 'continuation'],
  },
];

/**
 * Searches symbols by query string and optional category filter.
 */
export function searchLatexSymbols(
  query: string,
  category?: LatexSymbol['category'] | 'all',
): LatexSymbol[] {
  const q = query.trim().toLowerCase();
  return LATEX_SYMBOLS.filter((sym) => {
    if (category && category !== 'all' && sym.category !== category) {
      return false;
    }
    if (!q) return true;
    if (sym.command.toLowerCase().includes(q)) return true;
    if (sym.name.toLowerCase().includes(q)) return true;
    if (sym.symbol.includes(q)) return true;
    return sym.tags.some((tag) => tag.toLowerCase().includes(q));
  });
}
